<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" href="../css/bootstrap-new.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="../css/styles.css" />
	<script src="../js/jquery.min.js"></script>
	
</head>
<body>
<?php session_start();?>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?> 
		</div>
	
		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->
				
               </div>
				<!--Main Content area--> 
		        <div class="container-fluid col-sm-9 col-md-10">
		           <!--
						Write all
						your code
						here...
						It will appear in the content 
						section of webpage

						-->
						<?php
								
								$item_id = $_GET["item_id"];
								$_SESSION["item_id"] = $item_id;
								require_once "class.MySQL.php";           
            					$omysql=new MySQL();
            					$where =array("item_id like"=>$item_id."%");
            					$omysql->Select("items",$where);
            					if($omysql->records>0){
            						$result = $omysql->arrayedResult;
            						foreach($result as $row){
            							$pic = $row["pic_loc"];
            							$base_price=$row["base_price"];
            							$last_date=$row["last_date"];
            						}
            					}
            					$nmysql=new MySQL();
            					$limit=1;
				              	$nwhere = array("item_id like"=>$item_id."%");
					            $nmysql->Select("auction_bidder",$nwhere,"bid DESC",$limit);
					            if($nmysql->records>0){
					             	$result = $nmysql->arrayedResult;
					                foreach($result as $row){
					                	$cur_bid=$row["bid"];
					                }
					                
					            }else{
					                	$cur_bid=$base_price;
					                }
							?>
						<div class="productprice">

						    <div class="productpagecurrentbid">
						    <?php
						    	$splitTimeStamp = explode(" ",$last_date);
								$date = $splitTimeStamp[0];
								$time = $splitTimeStamp[1];
								date_default_timezone_set('Asia/Calcutta');
								$date = date('y-M-d h:m:s a', time());
								$date1 = '20'.$date;
								echo "\n";
								$datetime2 = new DateTime($date1);
								$datetime1 = new DateTime($last_date);
								$datreto = $datetime1->getTimestamp();
								$datefrom= $datetime2->getTimestamp();
								$x=$datetime1->diff($datetime2);
								$yy = $x->y;
								$mm = $x->m;
								$dd = $x->d;
								$hh = $x->h;
								$ii = $x->i;
								$ss = $x->s;
								$y=($yy*31536000)+($mm*2592000)+($dd*86400)+($hh*3600)+($ii*60)+$ss;
//$y=$x->format('%y years %m months %a days %h hours %i minutes %S seconds');
//echo $y;


						    ?>
						    </div>
						   <!-- <br></br> -->
						      <div class="productpagecurrentbid">
						      Current Bid : <?php echo $cur_bid ?>
						    </div>

						</div>
						<br></br>
						<form action = "save_bid.php" method="get">
							<?php
								// session_start();
								$item_id = $_GET["item_id"];
								$_SESSION["item_id"] = $item_id;
							?>
							<img border="5" src=<?php $pic ?> alt="Pulpit rock" width="300" height="228">

							<div class="control-group">
				            <label calss="control-label" for="select01">Place bid</label>
				            <div class= "formSmallTextbox">
				            <input type = "text" class="formTextbox" name="bid" id="bid" >
				            
				            </div>
				            <div class="form-actions">
                     
		           			<input type="submit" name="submit" class="btn btn-primary" value="Submit" id="submit">
		           			<script type="text/javascript">
		           				var a;
    							    var q = <?php echo json_encode($y); ?>;
    							    if(q > 0 && q < 900){
    							    	a="visible";
    							    }
    							    else{
    							    	a="hidden";
    							    }	
		           				document.getElementById('submit').style.visibility=a;
		           			</script>
		           			</div>
		           			<br></br>
		           			<ul class="productpagecart">

						    				    
						    <li>
						    	<a class="wish" href="#">
						        	Add to Watchlist
						        </a>
						    </li>

							</ul>

		               	</form>
		               	 <div class="col-sm-5">
	
		
				<div class="special" style="width:400px; height:250px;" >
					<div id="counter" style="position:relative; left:60px;">				
						<div id="shading" >&nbsp;</div>
					</div>		
					
					<script type="text/javascript" src="../js/C3counter.js"></script>
					<script type="text/javascript">
						// Default options 

            var p = <?php echo json_encode($y); ?>;
            if(p>0){
					   	C3Counter("counter", { startTime :p });
              setTimeout(check_time(){document.getElementById('submit').style.visibility='hidden';},(p*1000));
            }
					</script>
				</div>
</div>	  
				</div>
	</div>
	<!--All javascript placed at the end so that the page loads faster-->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>
	
</body>
</html>
