<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
	
</head>
<body>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?> 
		</div>
	
		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->
				<div class="col-sm-3 col-md-2 sidebar">
	                <ul class="nav nav-sidebar">
		                <li class="active"><a href="#">Search</a></li>
		                <li><a href="#">Profile</a></li>
		                <li><a href="#">Bulk Order</a></li>
		                <li><a href="#">Sell</a></li>
	                </ul>
                </div>
				<!--Main Content area--> 
		        <div class="container-fluid">
		           <!--
						Write all
						your code
						here...
						It will appear in the content 
						section of webpage
		           -->
		          <form action = "selling.php" method="get">
                   <div class="control-group">
		             <label class="control-label" for="select02" >Genre</label>
		             <div class="controls">
		             <select name="genre" id="genre">
		             <option></option>
		             <option value='fiction'>fiction</option>
		             <option>horror</option>
		             <option>romance</option>
		             <option>drama</option>
		             <option>Academic</option>
		             </select>
		             </div>
		            
                     </div>
                    <div class="control-group">
		            <label calss="control-label" for="select03">Name</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formSmallTextbox" name="name" id = "name">
                    
		            </div>
		            </div>
		            
		            <div class="control-group">
		            <label calss="control-label" for="select04">Author</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formSmallTextbox" name="author" id="author">
		            
		            </div>
		            </div>
		          <span >
		            <div class="control-group">
		            <label calss="control-label" for="select05">M.R.P.</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formSmallTextbox" name="mrp" id="mrp">
		            
		            </div>
		            </div>


		            <div class="control-group" >
		            <label calss="control-label" for="select06">Condition</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formSmallTextbox" name="condition" id="condition">
		            
		            </div>
		            </div>
                    </span>

		            <div class="control-group">
		            <label calss="control-label" for="select07">Description</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formTextbox" name="description"  size="150" id="description">
		            
		            </div>




		            </div>

                      <div class="form-actions">
                     
		           <input type="submit" name="submit" class="btn btn-primary" value="Auction" onClick="window.location.href='auction.php';
		            ">

                      
		              <input type="submit" name="submit" class="btn btn-primary" value="Sell" onClick="x=document.getElementById('sel').value;
		              ">

		             </div>
		             <!--<label class="control-label" for="select02">Choose Category</label>
		             <div class="controls">
		             <select name="category" id="sel">
		             <option></option>
		             <option value="Electronics">Electronics</option>
		             <option>Books</option>
		             <option>Stationery</option>
		             <option>Appliances</option>
		             <option>Others</option>
		             </select>
		             </div>-->

		             <!--<button onclick="window.location.href='auction.php'; ">Auction!</button>-->
		             <!-- <input type="submit" name="submit" class="controls" value="Submit" onClick="x=document.getElementById('sel').value;
		              if(x=='Electronics'){
		              window.location.href='electronic.php';
		              }
		              else if(x=='Books'){
		              window.location.href='sale.php';
		              }
		              else{
		               alert('byy');
		              }
		              ;">-->
		           
           


                <!--alert(document.getElementById('sel').value);

                 if(document.getElementById('sel').value == 'Books' 
		               then
		                window.location.href='login.php'; 
		                -->
                

                    
		        
	    		</div>
		</div>
	</div>
	<script type="text/javascript">
	function func(){
		alert(document.getElementById('sel').value);
		//alert(document.getElementById("select02").value);
		//<?php if($_REQUEST['category'] == 'Electronics'){ echo(' selected ');
	}
	</script>
	<!--All javascript placed at the end so that the page loads faster-->
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>

</body>
</html>
