<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
	
</head>
<body>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?> 
		</div>
	
		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->
				<div class="col-sm-3 col-md-2 sidebar">
	                <ul class="nav nav-sidebar">
		                <li class="active"><a href="#">Search</a></li>
		                <li><a href="#">Profile</a></li>
		                <li><a href="#">Bulk Order</a></li>
		                <li><a href="#">Sell</a></li>
	                </ul>
                </div>
				<!--Main Content area--> 
		        <div class="container-fluid">
		           <!--
						Write all
						your code
						here...
						It will appear in the content 
						section of webpage
		           -->
		          <form action = "retreive_data.php" method="get">
		          	<div class="control-group">
		             <label class="control-label" for="select02" >Choose Type</label>
		             <div class="controls">
		             <select name="type" id="type">
		             <option></option>
		             <option value='Mobile'>Mobile and gadgets</option>
		             <option>Laptops and gadgets</option>
		             <option>Household-Appliances</option>
		             <option>Appliances</option>
		             <option>Others</option>
		             </select>
		             </div>
		            
                     </div>
                     <div class="control-group">
		            <label calss="control-label" for="select03">Name</label>
		            <div class= "formSmallTextbox" >
		            <input type = "text" class="formSmallTextbox"  id="name" name="name">
                    </div>
		            </div>
                    <div class="control-group">
		            <label calss="control-label" for="select03">Brand</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formSmallTextbox" id="brand" name="brand">
                    
		            </div>
		            </div>
		            
		            <div class="control-group">
		            <label calss="control-label" for="select04">Model No</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formSmallTextbox" id="model" name="model">
		            
		            </div>
		            </div>
		          <span >
		            <div class="control-group">
		            <label calss="control-label" for="select05">M.R.P.</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formSmallTextbox" id="mrp" name="mrp">
		            
		            </div>
		            </div>

		            <div class="control-group">
		            <label calss="control-label" for="select03">Quantity</label>
		            <div class= "formSmallTextbox" >
		            <input type = "text" class="formSmallTextbox"  id="quantity" name="quantity">
                    </div>
		            </div>


		            <div class="control-group" >
		            <label calss="control-label" for="select06">Condition</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formSmallTextbox" id="condition" name="condition">
		            </div>
		            </div>
                    </span>

		            <div class="control-group">
		            <label calss="control-label" for="select07">Description</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formTextbox" id="description" name="description" size="150" >
		            </div>
		            </div>

		             <div class="control-group">
		            <label calss="control-label" for="select08">Base Price</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formTextbox" name="base_price" id="base_price" >
		            
		            </div>
		            

		           <!-- <div class="control-group">
		            <label calss="control-label" for="select09">Start Date(yyyy-mm-dd)</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formTextbox" name="start_date" id="start_date" >
		            
		            </div>-->

		             <div class="control-group">
		            <label calss="control-label" for="select10">Close Date(yyyy-mm-dd)</label>
		            <div class= "formSmallTextbox">
		            <input type = "text" class="formTextbox" name="close_date" id="close_date" >
		            
		            </div>


                    
		             
		             	Upload Picture 1 : <input type="file" id="image1" accept="image/*">
		            
		             <script type="text/javascript">
                     function check1(event)
                     {
                     if (!document.getElementById('image1').value.match(/.*\.PNG|.*\.GIF|.*\.JPEG|.*\.jpg/) )
                      {
					  alert('File must have suitable extension. Please try again.');
					    return false;
					    }
					    return true;
					  }
					</script>

					<script type="text/javascript">
                     function check2(event)
                     {
                     if (!document.getElementById('image2').value.match(/.*\.PNG/) || !document.getElementById('image2').value.match(/.*\.GIF/) || !document.getElementById('image2').value.match(/.*\.JPEG/) || !document.getElementById('image2').value.match(/.*\.JPG/))
                      {
					  alert('File must have suitable extension. Please try again.');
					    return false;
					    }
					    return true;
					  }
					</script>

					<script type="text/javascript">
                     function check3(event)
                     {
                     if (!document.getElementById('image3').value.match(/.*\.PNG/) || !document.getElementById('image3').value.match(/.*\.GIF/) || !document.getElementById('image3').value.match(/.*\.JPEG/) || !document.getElementById('image3').value.match(/.*\.JPG/))
                      {
					  alert('File must have suitable extension. Please try again.');
					    return false;
					    }
					    return true;
					  }
					</script>

		             
		             	Upload Picture 2 : <input type="file" id="myFile" accept="image/*">
		            

		             
		             	Upload Picture 3 : <input type="file" id="myFile" accept="image/*">
		           
		             
		             
		             <!--<label class="control-label" for="select02">Choose Category</label>
		             <div class="controls">
		             <select name="category" id="sel">
		             <option></option>
		             <option value="Electronics">Electronics</option>
		             <option>Books</option>
		             <option>Stationery</option>
		             <option>Appliances</option>
		             <option>Others</option>
		             </select>
		             </div>-->

		             <!--<button onclick="window.location.href='auction.php'; ">Auction!</button>-->
		             <!-- <input type="submit" name="submit" class="controls" value="Submit" onClick="x=document.getElementById('sel').value;
		              if(x=='Electronics'){
		              window.location.href='electronic.php';
		              }
		              else if(x=='Books'){
		              window.location.href='sale.php';
		              }
		              else{
		               alert('byy');
		              }
		              ;">-->
		           
           


                <!--alert(document.getElementById('sel').value);

                 if(document.getElementById('sel').value == 'Books' 
		               then
		                window.location.href='login.php'; 
		                -->
                

                      <div class="form-actions">
                     
		           <input type="submit" name="submit" class="btn btn-primary" value="Submit">

                      
		              
                      </form>
		              
		             

		             </div>
		        
	    		</div>


		</div>

	</div>
	

	<!--<script>
	function myFunction(){
    alert('hii');
    alert(document.getElementById('name').value);
     }
     
	</script>-->

	<!--All javascript placed at the end so that the page loads faster-->
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>

</body>
</html>
