<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" href="../css/bootstrap-new.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="../css/styles.css" />
	<link rel="stylesheet" type="text/css" href="../css/bootstrap-magnify.min.css">
	<script src="../js/jquery.min.js"></script>
	
</head>
<body>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?> 
		</div>
	<?php
								
								$item_id = $_GET["item_id"];
								//echo $item_id;
								//$item_id = 24;
								$_SESSION["item_id"] = $item_id;
								require_once "class.MySQL.php";           
            					$omysql=new MySQL();

            					if(isset($_SESSION['authentication']))
            					{
            						$row=$omysql->ExecuteSQL("SELECT * from watch_list where user_nm='".$_SESSION['user_nm']."' and item_id='$item_id'");
            						if($row!="true")
            							{
            							    $row=$omysql->ExecuteSQL("SELECT `cost` from items where item_id='$item_id'");
            							    $omysql->ExecuteSQL("UPDATE watch_list SET `previous_cost`='".$row[0]["cost"]."' where item_id='$item_id' and user_nm='".$_SESSION['user_nm']."'");
            							}
            					}


            					
            					$where =array("item_id like"=>$item_id."%");
            					$omysql->Select("items",$where);
            					if($omysql->records>0){
            						$result = $omysql->arrayedResult;
            						foreach($result as $row){
            							$pic_loc = $row["pic_loc"];
            							$base_price=$row["base_price"];
            							$last_date=$row["last_date"];
            							$name=$row["item_nm"];
            							$model=$row["model"];
            							$mrp=$row["cost"];
            							$condition=$row["item_condition"];
            							$start_date=$row["start_date"];
            							$description=$row['description'];
            						}
            						$split_des=explode(";",$description);
            						$split_des1=explode(":",$split_des[0]);
            						$des=$split_des1[1];
            					}
            					//echo $base_price;
            					//echo $last_date;
            					$nmysql=new MySQL();
            					$limit=1;
				              	$nwhere = array("item_id like"=>$item_id."%");
					            $nmysql->Select("auction_bidder",$nwhere,"bid DESC",$limit);
					            if($nmysql->records>0){
					             	$result = $nmysql->arrayedResult;
					                foreach($result as $row){
					                	$cur_bid=$row["bid"];
					                }
					                
					            }else{
					                	$cur_bid=$base_price;
					                }
							?>
							</div>
						<div class="productprice">

						    <div class="productpagecurrentbid">
						    <?php
						    	$splitTimeStamp = explode(" ",$last_date);
								$date = $splitTimeStamp[0];
								$time = $splitTimeStamp[1];
								date_default_timezone_set('Asia/Calcutta');
								$date = date('y-M-d h:m:s a', time());
								$date1 = '20'.$date;
								//echo "\n";
								$datetime3 = new DateTime($start_date);
								$datetime2 = new DateTime($date1);
								$datetime1 = new DateTime($last_date);
							if($datetime3->format('U') > $datetime2->format('U')){
								$f=$datetime3->diff($datetime2);
								$fy = $f->y;
								$fm = $f->m;
								$fd = $f->d;
								$fh = $f->h;
								$fi = $f->i;
								$fs = $f->s;
								$g=($fy*31536000)+($fm*2592000)+($fd*86400)+($fh*3600)+($fi*60)+$fs;
							}
							else{
								$g = 0;
							}
							//echo $g;
							if($datetime1->format('U') > $datetime2->format('U')){
								$x=$datetime1->diff($datetime2);
								$yy = $x->y;
								$mm = $x->m;
								$dd = $x->d;
								$hh = $x->h;
								$ii = $x->i;
								$ss = $x->s;
								$y=($yy*31536000)+($mm*2592000)+($dd*86400)+($hh*3600)+($ii*60)+$ss;
							}
							elseif($g != 0) {
								$y = 0;
							}
							else{
								$y = 0;
							}
//$y=$x->format('%y years %m months %a days %h hours %i minutes %S seconds');
//echo $y;


						    ?>
						    <?php
								//session_start();
								//$item_id = $_GET["item_id"];
								$_SESSION["cur_bid"] = $cur_bid;
								$_SESSION["item_id"] = $item_id;
							?>
		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->
				<div class="col-sm-3 col-md-2 sidebar">
				<div class="mag">
                                                <?php $pic = "../upload/".$pic_loc; ?>
                                                <img data-toggle="magnify" src="<?php echo $pic;?>" alt="" title="" width="300" height="1000" class="img-thumbnail">

                                           </div>
	             <!-- <img border="5" data-toggle="magnify" src=<?php// echo "../upload/".$pic ?> alt="Pulpit rock" width="250"  align="right" onmouseover="this.width=450;this.height=330;" onmouseout="this.width=100;this.height=100">  -->
                </div>
				<!-- <div class="col-sm-3 col-md-2 sidebar">
	               <img border="5" src=<?php //echo "../upload/".$pic ?> alt="Pulpit rock" width="250" height="auto" align="right">  
                </div> -->
				<!--Main Content area--> 
		        <div class="container-fluid col-sm-9 col-md-10">
		           <!--
						Write all
						your code
						here...
						It will appear in the content 
						section of webpage
		           -->
                    <div>
						
						    </div>

                    <form action = "save_bid.php" method="get" class="form-horizontal" id="usrform" enctype="multipart/form-data">
                    <fieldset>
                    	


                  
                    <div class="form-group">
		                 <label class="col-sm-2 control-label" for="select03" >Current Bid :</label>
		            
		            
		            <div class="col-sm-5">
		             <label class="col-sm-2 control-label" for="select03" ><?php echo $cur_bid ?></label>
		             </div>
		             </div>
                      
                        <div class="form-group">
		                         <label class="col-sm-2 control-label" for="select03" >Name:</label>
		            
		            
		            <div class="col-sm-5">
		             <label class="col-sm-2 control-label" for="select03" ><?php echo $name ?></label>
		             
		             </div>
		             </div>
                   

                      <div class="form-group">
		                 <label class="col-sm-2 control-label" for="select03" >Condition:</label>
		            
		            
		            <div class="col-sm-5">
		             <label class="col-sm-2 control-label" for="select03"><?php echo $condition ?></label>
		             
		             </div>
		             </div>
		             <div class="form-group">
		              <label class="col-sm-2 control-label" for="select03" >Mrp:</label>
		            
		            
		            <div class="col-sm-5">
		             <label class="col-sm-2 control-label" for="select03" ><?php echo $mrp ?></label>
		             
		             </div>
		             </div>
         				
         			<div class="form-group">
		                         <label class="col-sm-2 control-label" for="select03" >Description:</label>
		            
		            
		            <div class="col-sm-5">
		             <label class="col-sm-2 control-label" for="select03" ><?php echo $des ?></label>
		             
		             </div>
		             </div>




                  <div class="form-group">
				            <label class="col-sm-2 control-label" for="select01">Place bid</label>
				             <div class="col-sm-5">
		                    <input type = "text" class="form-control"  id="bid" name="bid" style="height:30px;font-size:14pt;width:140px;" > 
				            </div>
				            </div>
				             
     


				            <div class="form-actions">
                            <div class="col-sm-1">
		           			<input type="submit" name="submit" class="btn btn-primary" value="Submit" id="submit" style="height:30px;width:60px;" disabled="true">
    						</div>
		           			</div>
		           			          			
		                <div class="form-actions">
		           <div class="col-sm-5">
	
	                 <button type="button" class="btn btn-primary btn-lg" onClick="add_watch('<?php echo $item_id;?>')" @brand-success: #5cb85c; >Add To Watch List</button>	
						<div class="special" style="width:400px; height:250px ;" >
								<div id="counter" style="position:relative; left:60px ;">				
										<div id="shading" >&nbsp;</div>
								</div>		
					
						</div>
					</div>	  
						</div>
						
				 			</div>


		              </fieldset>
                      </form>
		              
		             

		             </div>
		        
	    		</div>


		</div>

	
	

	<!--<script>
	function myFunction(){
    alert('hii');
    alert(document.getElementById('name').value);
     }
     
	</script>-->

	<!--All javascript placed at the end so that the page loads faster-->
	<script type="text/javascript" src="../js/C3counter.js"></script>
					<script type="text/javascript">
						// Default options 

                     var p = <?php echo json_encode($y); ?>;
            //if(p>0){
					   	C3Counter("counter", { startTime :p });
              //setTimeout(check_time(){document.getElementById('submit').style.visibility='hidden';},(p*1000));
            //}
					</script>
					<script type="text/javascript" src="../js/jquery.min.js"></script>
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>
	<script>
	var y = <?php echo json_encode($y); ?>;
	setTimeout(function(){document.getElementById('submit').disabled =true;},(y*1000));
	</script>

	<script>
	var h = <?php echo json_encode($g); ?>;
	setTimeout(function(){document.getElementById('submit').disabled =false;},(h*1000));
	</script>
	<script type="text/javascript">
		function add_watch(item_id)
	    {
            // alert("IN ADD_watch FUNC");
            $.ajax({
                    url: "detail_addwatch.php",
                    dataType: "json",
                    type: "GET",
                    data: {
                            item_id : item_id
                            },
                    success: function(response_data){
                    console.log(response_data);
                        if(response_data=="1")
                        {
                           // alert("Added, reloading page");
                            //window.location.reload();
                        }
                        else if(response_data=="0")
                        {
                            alert("Could not be added!!!");
                        }
                        // as we have written datatype as json so jquery automatically converts the result
                        //from json... so responce_data is not json its already parsed
                    },
                    /*As of jQuery 1.5, the $.ajax() method returns the jqXHR object, which is a superset of the XMLHTTPRequest object.
                    error:  Function( jqXHR jqXHR, String textStatus, String errorThrown )
                    */
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
	    }
	</script>

</body>
</html>
