<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Invoice</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
</head>
<body>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?>
		</div>
        <?php
            require_once "class.MySQL.php";
            $omysql=new MySQL();
            $order_id="20140414CE48";
            //////////////////Selecting data corresponding to the order_id from orders table//////////////////////////
            $from="orders";
            $items=array(array("item_id","qty","delivery"));
            $where = array("order_id="=>$order_id);
            $omysql->Select($from,$where);
            $o_res = $omysql->arrayedResult;
            $o_rows=$omysql->affected;
            for($i=0;$i<$o_rows;$i++){
               $items[$i]['item_id']=$o_res[$i]["item_id"];
               $items[$i]['qty']=$o_res[$i]["qty"];
               $username=$o_res[$i]["user_nm"];
               $o_address=$o_res[$i]["address"];
               $date=$o_res[$i]["order_time"];
            }
         ?>
		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->

				<!--Main Content area-->
		        <!--<div class="container-fluid">
		           <!--
						Write all
						your code
						here...
						It will appear in the content
						section of webpage
		           -->
		            <div class="col-sm-5 col-md-5" >
		                <br><h4>INVOICE</h4>
                    </div>
                    <div class="col-sm-2 col-md-2"></div>
                    <div class="col-sm-5 col-md-5" align="right" >
                        <h3>Online Trading</h3>
                    </div>
                    <hr>
                    <br>
		           <div class="well">
		               <b>ORDER NO: <?php echo $order_id;?></b>
		           </div><br>
                    <div class="col-sm-5 col-md-4" >
                        <b>User Name: </b><?php echo $username ?>
                         <br><b>Shipping Address</b><br><?php echo $o_address ?>
                    </div>
                    <div class="col-sm-2 col-md-3"></div>
                    <div class="col-sm-5 col-md-5" align="right" >
                        Date: <?php echo $date;?>
                    </div>
                    <div class="col-sm-12 col-md-12">
                        <br><br>
		           <table class="table table-bordered">
		               <tbody>
		                   <tr>
                                <th>#</th>
                                <th>Item</th>
                                <th>Unit Price</th>
                                <th>Tax</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                            <?php

                            $entries = $o_rows; //number of items in placed order
                            $sno = 0;
                            $from = "items";
                            $grandtot = 0;
                            //fill table
                            while($sno < $entries)
                            {
                                echo "<tr>";
                                $id = $items[$sno]["item_id"]; //item_id of bought item
                                $quantity = $items[$sno]["qty"]; //qty bought
                                ///search for item details
                                $where = array("item_id like"=>$id);
                                $omysql->Select($from, $where);
                                $res = $omysql->arrayedResult;
                                $tot = $res[0]["cost"] + (($res[0]["cost"]*$res[0]["tax"])/100);
                                $grandtot+=$tot;
                                $sno++;
                                echo "<td>".$sno."</td>
                                <td>".$res[0]["item_nm"]."</td>
                                <td>₹".$res[0]["cost"]."</td>
                                <td>".$res[0]["tax"]."%</td>
                                <td>".$quantity."</td>
                                <td>₹".$tot."</td>";
                                echo "</tr>";

                            }
                            ?>
                            <tr><td></td><td></td><td></td>
                                <td><b>Grand Total</b>: </td><td></td>
                                <td><b>₹<?php echo $grandtot; ?></b></td>
                            </tr>
		               </tbody>
                    </table>
                    </div>
                    <div class="col-sm-12 col-md-12">
                        Thanks for your purchase!
                    </div>
                   <!-- <div="col-sm-12 col-md-12">
                    <button class="btn btn-success" type="button" onclick="pdf();" name="pdf" id="pdf">Print</button>
                    </div> -->
	    		</div>
		<!--</div>-->
	</div>
	<!--All javascript placed at the end so that the page loads faster-->
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>

</body>
</html>
