<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
</head>
<body>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?> 
		</div>
	
		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->
				
				<!--Main Content area--> 
		        <div class="container-fluid col-sm-9 col-md-9">
		        	
		        <div>
		        		<div>
		        		 <a name="Profile"> </a>
		        		 <h2>Profile </h2>
		        	    </div>

		        	 <div class="lastUnit tmargin20">
		        		<dl>
		        		  <dt> <a href="#" onclick="toggle('box3')">What is 'Profile'? How do I update my information?</a> </dt>
                            <div id="box3" style="display: none;">
                            	<p>It is easy to update your account and view your orders any time through 'Profile'. </p>
                                <p>Your Profile allows you complete control over your transactions </p>
                                <li>Manage/edit your personal data like address, phone numbers, email ids</li>
								<li>Change your password</li>
                            </div>
                          <dt> <a href="#" onclick="toggle('box4')">Can I order a product that is 'Out of Stock'?</a> </dt>
                            <div id="box4" style="display: none;">
                                <p> Unfortunately, products listed as 'Out of Stock' are not available for sale. You can add that item 
                                into wishlist whenever that item will be availabe we will inform you via notification.</p>
                            </div>

                          <dt> <a href="#" onclick="toggle('box7')">what is wishlist and watchlist?</a> </dt>
                            <div id="box7" style="display: none;">
                                <p> If any item currently not present in stock then u canadd that item to wishlist,
                                whenever that item will be availabe we will inform you via notification.</p>
                                <p>If u want to keep track of auction of any item u can add that item to watchlist. </p>
                            </div>
                        </dl>
                      </div>
					</div>

								<hr>



		        	<div>
		        		<div>
		        		 <a name="shopping"> </a>
		        		 <h2>Shopping </h2>
		        	    </div>

		        	 <div class="lastUnit tmargin20">
		        		<dl>
		        		  <dt> <a href="#" onclick="toggle('box1')">Is it necessary to have an account to shop?</a> </dt>
                            <div id="box1" style="display: none;">
                            <p>Yes it is necessary by creating your own account, you can enjoy a personalized shopping experience,
                             including recommendations, wishlist and a public wishlist.</p> 
                            </div>
                         
                        </dl>
                      </div>
					</div>
							<hr>


		        	<div>
		        		<div>
		        		 <a name="Payments"> </a>
		        		 <h2>Payments </h2>
		        	    </div>

		        	 <div class="lastUnit tmargin20">
		        		<dl>
		        		  <dt> <a href="#" onclick="toggle('box5')">How do I pay for a purchase?</a> </dt>
                            <div id="box5" style="display: none;">
                            <p></p> 
                            </div>
                          
                        </dl>
                      </div>
					</div>

							<hr>
		        	<div>
		        		<div>
		        		 <a name="Payments"> </a>
		        		 <h2>Auction </h2>
		        	    </div>

		        	 <div class="lastUnit tmargin20">
		        		<dl>
		        		  <dt> <a href="#" onclick="toggle('box8')">How can i sell my item in Auction?</a> </dt>
                            <div id="box8" style="display: none;">
                            <p>TO Sell your item by auction first you have to creat an account then by clicking on Auction you will be 
                            redirected to a page where you have to choose catagory of your item and after that you have to fill some 
                            information related to your item. After doing that your have completed your part, whenever any buyer bid 
                            for your item we will notify you.</p> 
                            </div>
                          <dt> <a href="#" onclick="toggle('box9')">HOw can I buy any item through Auctin?</a> </dt>
                            <div id="box9" style="display: none;">
                            <p>Whenever you will search for any item if that item is available for auction after clicking on that
                            item you will be redireced to a page where you can place a bid if the deadline for that item is not over.
                            At the end if you are the person eith highest bid we will notify you.  </p>

                            </div>
                        </dl>
                      </div>
					</div>


							<hr>


		           <!--
						Write all
						your code
						here...
						It will appear in the content 
						section of webpage
		           -->
		        
	    		</div>
		</div>
	</div>
	<!--All javascript placed at the end so that the page loads faster-->
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>
</body>
</html>

<script language="JavaScript">
	function toggle(id) {
		var state = document.getElementById(id).style.display;
			if (state == 'block') {
				document.getElementById(id).style.display = 'none';
			} else {
				document.getElementById(id).style.display = 'block';
			}
		}
</script>

