<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>history</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
	   <!-- <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
-->


</head>
<body>
    <?php require_once "class.MySQL.php"; ?>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?>
		</div>

		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->

				<!--Main Content area-->
                    <?php
                        $omysql=new MySQL();
                        session_start();
                        $usernm = $_SESSION['user_nm'];
                        $auth = $_SESSION['authentication'];
                        $where=array("user_nm like"=>$usernm);
                        $from = "orders";
                        $orderBy = "order_id DESC";
                        $omysql->Select($from, $where, $orderBy);
                        $rows = $omysql->records;
                        $res1 = $omysql->arrayedResult;
                        ?>
		        <div class="container-fluid col-sm-12 col-md-12">
		            <ul class="nav nav-tabs" id="mytabs">
                    <li class="active">
                    <a href="#tab_a" id="rec_order">RECENT ORDERS <small>(Last 2 Months)</small></a></li>
                    <li><a href="#tab_b" id="past_order">PAST ORDERS</a></li>
                    </ul>
                    <div class="tab-content">
                    <div class="tab-pane active" id="tab_a">
                    <table class="table table striped">
                        <tbody>
                        <!--<h4>In recent Orders</h4>-->
                        <?php
                            $i=0;
                            $j=0;
                            $arr = array_fill_keys(array('user_nm','qty','item_id','order_id','order_time','delivery_time','status','txn_id','address','delivery_type'),'');
                            $cur_id = '';
                            $prev_id = '';
                            $cur_date = date("Y/m/d");
                            $entries=0;
                            while($i<$rows)
                            {
                                //echo $res1[$i]["order_id"]."<br>";
                                $timestamp = strtotime($res1[$i]["order_time"]);
                                $date = date('Y/m/d', $timestamp);
                                //echo $date; echo "&nbsp;".$res1[$i]["order_id"]; echo "<br>";
                                if( strtotime($date) > strtotime("-2 months"))
                                {
                                    //echo "Within 2 months<br>";
                                    $entries++;
                                    $cur_id = $res1[$i]["order_id"];
                                    if(trim($cur_id)==trim($prev_id))
                                    {
                                        //same order id as last row
                                       // echo"same id<br>";
                                        $arr[$j]=$res1[$i];
                                        $j++;
                                    }  //if(trim($cur_id)==trim($prev_id))
                                    else
                                    {
                                        //echo"different id found<br>";
                                        if($j==0)
                                        {
                                            $arr[$j]=$res1[$i];
                                            $j++;
                                            $prev_id = $cur_id;
                                        }
                                        //different order than last found
                                        elseif($j>0)
                                        {
                                            $from = "items";
                                            echo "<tr><td><h5><b>Order ID: ".$prev_id."</b></h5></td><td></td><td></td><td></td><td></td></tr>";
                                            for($k=0;$k<$j;$k++)
                                            {
                                                $item_id = $arr[$k]["item_id"];
                                                $where = array("item_id like"=>$item_id);
                                                $omysql->Select($from, $where);
                                                $res2 = $omysql->arrayedResult;
                                                $total = $arr[$k]["qty"]*$res2[0]["cost"];
                                                $tax = (($res2[0]["tax"]/100)*$total);
                                                $total+=$tax;
                                                $pic_loc = "../upload/".$res2[0]["pic_loc"];
                                                echo "<tr>
                                                <td>
                                                <img src=".'"'.$pic_loc.'"'." width=".'"100"'."height=".'"100"'.">
                                                </td>
                                                <td>
                                                <h4><a href=".'"sale.php?item_id='.$item_id.'"'." >".$res2[0]["item_nm"]."</a></h4>"
                                                ."\n"."<small>Item price: ₹".$res2[0]["cost"]
                                                ."<br>"."Condition: ".$res2[0]["item_condition"]."
                                                </small></td>
                                                <td>
                                                Quantity: ".$arr[$k]["qty"]. "
                                                </td>
                                                <td><b> &nbsp;&nbsp;₹".$total."<b><br></td>
                                                <td>";
                                                if(trim($arr[$k]["status"])=='Delivered')
                                                {
                                                    echo "<b>Delivered on ".date('Y/m/d',strtotime($arr[$k]["delivery_time"]))."<br></b>";
                                                }
                                                elseif(trim($arr[$k]["status"])=='Not Delivered')
                                                {
                                                    if(strtotime(date('Y/m/d',strtotime($arr[$k]["order_time"]))) > strtotime("-10 days"))
                                                    {
                                                        //allow confirmation of delivery if order < 10 days old
                                                         //echo "within 10 days".$arr[$k]["order_time"];
                                                         echo "<b>Not Delivered Yet<br></b>
                                                        <form>";
                                                        echo "<input type=".'"'."radio".'"'."value=".'"'."Confirm".'"'." onClick=".'"'."confirm('".$item_id."')".'"'.">Confirm Delivery</input>
                                                        <br>";

                                                        if(trim($arr[$k]["delivery_type"])=='normal' && strtotime(date('Y/m/d',strtotime($arr[$k]["order_time"]))) > strtotime("-2 days"))
                                                        {
                                                            //allow cancellation of order if normal delivery and order < 2 days old
                                                            echo "<input type=".'"'."radio".'"'."value=".'"'."Cancel".'"'." onClick=".'"'."cancel_delivery('".$item_id."')".'"'.">Cancel Delivery</input>
                                                            <br>";
                                                        }
                                                        echo "</form>";
                                                    }
                                                    else
                                                    {
                                                        //force confirm delivery coz >=10 days old order
                                                        $where=array("user_nm like"=>$usernm,"item_id"=>$arr[$k]["item_id"]);
                                                        $tym = date("Y/m/d");
                                                        $set=array("status"=>"Delivered","delivery_time"=>$tym);
                                                        $omysql->Update("orders", $set, $where);
                                                        //echo "updated: ".$omysql->affected."rows<br>";
                                                        echo "<b>Delivered on ".$tym."</b><br>";
                                                    }
                                                }
                                                echo "</td>
                                                </tr>";
                                                }//for($k=0;$k<$j;$k++)
                                                //echo "Done with order<br>";
                                                $j=0;
                                                $arr = array_fill_keys(array('user_nm','qty','item_id','order_id','order_time','delivery_time','status','txn_id','address','delivery_type'),'');
                                                $arr[$j]=$res1[$i];
                                                $prev_id = $cur_id;
                                                //$cur_id = '';
                                                $j++;
                                        }//elseif($j>0)
                                    }//else
                                 }//if( strtotime($date) > strtotime("-2 months"))
                                $i++;
                            }// while($i<$rows)
                            if($j>0)
                            {
                                echo "<tr><td><h5><b>Order ID: ".$prev_id."</b></h5></td><td><td></td></td><td></td><td></td></tr>";
                                for($k=0;$k<$j;$k++)
                                {
                                $item_id = $arr[$k]["item_id"];
                                $where = array("item_id like"=>$item_id);
                                $omysql->Select("items", $where);
                                $res2 = $omysql->arrayedResult;
                                $total = $arr[$k]["qty"]*$res2[0]["cost"];
                                $tax = (($res2[0]["tax"]/100)*$total);
                                $total+=$tax;
                                $pic_loc ="../upload/".$res2[0]["pic_loc"];
                                echo "<tr>
                                <td>
                                <img src=".'"'.$pic_loc.'"'." width=".'"100"'."height=".'"100"'.">
                                </td>
                                <td>
                                <h4><a href=".'"sale.php?item_id='.$item_id.'"'.">".$res2[0]["item_nm"]."</a></h4>"
                                ."\n"."<small>Item price: ₹".$res2[0]["cost"]
                                ."<br>"."Condition: ".$res2[0]["item_condition"]."
                                </small></td>
                                <td>
                                Quantity: ".$arr[$k]["qty"]. "
                                </td>
                                <td><b> &nbsp;&nbsp;₹".$total."<b><br></td>
                                <td>";
                                if(trim($arr[$k]["status"])=='Delivered')
                                {
                                    echo "<b>Delivered on ".date('Y/m/d',strtotime($arr[$k]["delivery_time"]))."</b><br>";
                                }
                                elseif(trim($arr[$k]["status"])=='Not Delivered')
                                {
                                    if(strtotime(date('Y/m/d',strtotime($arr[$k]["order_time"]))) > strtotime("-10 days"))
                                    {
                                        //allow confirmation of delivery if order < 10 days old
                                        echo "<b>Not Delivered Yet</b><br>
                                        <form>";
                                        echo "<input type=".'"'."radio".'"'."value=".'"'."Confirm".'"'." onClick=".'"'."confirm('".$item_id."')".'"'.">Confirm Delivery</input>
                                        <br>";
                                        if(trim($arr[$k]["delivery_type"])=='normal' && strtotime(date('Y/m/d',strtotime($arr[$k]["order_time"]))) > strtotime("-2 days"))
                                        {
                                            //allow cancellation of order if normal delivery and order < 2 days old
                                            echo "<input type=".'"'."radio".'"'."value=".'"'."Cancel".'"'." onClick=".'"'."cancel_delivery('".$item_id."')".'"'.">Cancel Delivery</input>
                                            <br>";
                                        }
                                        echo "</form>";
                                    }
                                    else
                                    {
                                        //force confirm delivery coz >=10 days old order
                                        $where=array("user_nm like"=>$usernm,"AND item_id like"=>$arr[$k]["item_id"]);
                                        $tym = date("Y/m/d");
                                        $set=array("status"=>"Delivered","delivery_time"=>$tym);
                                        $omysql->Update("orders", $set, $where);
                                        echo "<b>Delivered on ".$tym."<br></b>";
                                    }

                                }
                                echo "</td>
                                </tr>";
                                }//for($k=0;$k<$j;$k++)
                                $j=0;
                                //$arr = array_fill_keys(array('user_nm','qty','item_id','order_id','order_time','delivery_time','status'),'');
                            }//if($j>0)
                            ?>
                        </tbody>
                    </table>
                    <?php if($entries==0)
                          {
                            echo "Oops, you have no recent orders to display!";
                          }
                    ?>
                    </div>
                    <div class="tab-pane" id="tab_b">
                    <table class="table table striped">
                        <tbody>
                        <!--<h4>In Past Orders</h4>-->
                        <?php
                            $i=0;
                            $j=0;
                            $arr = array_fill_keys(array('user_nm','qty','item_id','order_id','order_time','delivery_time','status','txn_id','address','delivery_type'),'');
                            $cur_id = '';
                            $prev_id = '';
                            $cur_date = date("Y/m/d");
                            $entries = 0;
                            while($i<$rows)
                            {
                                $timestamp = strtotime($res1[$i]["order_time"]);
                                $date = date('Y/m/d', $timestamp);

                                //echo $date; echo "&nbsp;".$res1[$i]["order_id"]; echo "<br>";
                                if( strtotime($date) <= strtotime("-2 months"))
                                {
                                    //echo "Not Within 2 months<br>";
                                    $cur_id = $res1[$i]["order_id"];
                                    $entries++;
                                    if(trim($cur_id)==trim($prev_id))
                                    {
                                        //same order id as last row
                                       // echo"same id<br>";
                                        $arr[$j]=$res1[$i];
                                        $j++;
                                    }  //if(trim($cur_id)==trim($prev_id))
                                    else
                                    {
                                        //echo"different id found<br>";
                                        if($j==0)
                                        {
                                            $arr[$j]=$res1[$i];
                                            $j++;
                                            $prev_id = $cur_id;
                                        }
                                        //different order than last found
                                        elseif($j>0)
                                        {
                                            $from = "items";
                                            echo "<tr><td><h5><b>Order ID: ".$prev_id."</b></h5></td><td></td><td></td><td></td><td></td></tr>";
                                            for($k=0;$k<$j;$k++)
                                            {
                                                $item_id = $arr[$k]["item_id"];
                                                $where = array("item_id like"=>$item_id);
                                                $omysql->Select($from, $where);
                                                $res2 = $omysql->arrayedResult;
                                                $total = $arr[$k]["qty"]*$res2[0]["cost"];
                                                $tax = (($res2[0]["tax"]/100)*$total);
                                                $total+=$tax;
                                                $pic_loc = "../upload/".$res2[0]["pic_loc"];
                                                echo "<tr>
                                                <td>
                                                <img src=".'"'.$pic_loc.'"'." width=".'"100"'."height=".'"100"'.">
                                                </td>
                                                <td>
                                                <h4><a href=".'"sale.php?item_id='.$item_id.'"'." >".$res2[0]["item_nm"]."</a></h4>"
                                                ."\n"."<small>Item price: ₹".$res2[0]["cost"]
                                                ."<br>"."Condition: ".$res2[0]["item_condition"]."
                                                </small></td>
                                                <td>
                                                Quantity: ".$arr[$k]["qty"]. "
                                                </td>
                                                <td><b> &nbsp;&nbsp;₹".$total."<b><br></td>
                                                <td>";
                                                if(trim($arr[$k]["status"])=='Delivered')
                                                {
                                                    echo "<b>Delivered on ".date('Y/m/d',strtotime($arr[$k]["delivery_time"]))."</b><br>";
                                                }
                                                elseif(trim($arr[$k]["status"])=='Not Delivered')
                                                {
                                                   // echo "Not Delivered<br>
                                                    //";
                                                }
                                                echo "</td>
                                                </tr>";
                                                }//for($k=0;$k<$j;$k++)
                                                //echo "Done with order<br>";
                                                $j=0;
                                                $arr = array_fill_keys(array('user_nm','qty','item_id','order_id','order_time','delivery_time','status','txn_id','address','delivery_type'),'');
                                                $arr[$j]=$res1[$i];
                                                $prev_id = $cur_id;
                                                //$cur_id = '';
                                                $j++;
                                        }//elseif($j>0)
                                    }//else
                                 }//if( strtotime($date) > strtotime("-2 months"))
                                $i++;
                            }// while($i<$rows)
                            if($j>0)
                            {
                                echo "<tr><td><h5><b>Order ID: ".$prev_id."</b></h5></td><td><td></td></td><td></td><td></td></tr>";
                                for($k=0;$k<$j;$k++)
                                {
                                $item_id = $arr[$k]["item_id"];
                                $where = array("item_id like"=>$item_id);
                                $omysql->Select("items", $where);
                                $res2 = $omysql->arrayedResult;
                                $total = $arr[$k]["qty"]*$res2[0]["cost"];
                                $tax = (($res2[0]["tax"]/100)*$total);
                                $total+=$tax;
                                $pic_loc = "../upload/".$res2[0]["pic_loc"];
                                echo "<tr>
                                <td>
                                <img src=".'"'.$pic_loc.'"'." width=".'"100"'."height=".'"100"'.">
                                </td>
                                <td>
                                <h4><a href=".'"sale.php?item_id='.$item_id.'"'." >".$res2[0]["item_nm"]."</a></h4>"
                                ."\n"."<small>Item price: ₹".$res2[0]["cost"]
                                ."<br>"."Condition: ".$res2[0]["item_condition"]."
                                </small></td>
                                <td>
                                Quantity: ".$arr[$k]["qty"]. "
                                </td>
                                <td><b> &nbsp;&nbsp;₹".$total."<b><br></td>
                                 <td>";
                                $dt = date('Y/m/d',strtotime($arr[$k]["delivery_time"]));
                                if(trim($arr[$k]["status"])=='Delivered')
                                {
                                    echo "<b>Delivered on ".$dt."</b><br>";
                                }
                                elseif(trim($arr[$k]["status"])=='Not Delivered')
                                {
                                    // echo "Not Delivered<br>
                                    //";
                                }
                                echo "</td>
                                </tr>";
                                }//for($k=0;$k<$j;$k++)
                                $j=0;
                            }//if($j>0)
                            ?>
                        </tbody>
                    </table>
                    <?php if($entries==0)
                          {
                            echo "Oops, you have no past orders to display!";
                          }
                    ?>
                    </div>
                    </div>
		           <!--
						Write all
						your code
						here...
						It will appear in the content
						section of webpage
		           -->

	    		</div>
		</div>
	</div>
	<!--All javascript placed at the end so that the page loads faster-->
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	    <script type="text/javascript">

       function confirm(item_id){
            //alert("Inside func confirm");
            $.ajax({
                    url: "confirmajax.php",
                    dataType: "json",
                    type: "GET",
                    data: {
                            item_id : item_id
                            },
                    success: function(response_data){
                    console.log(response_data);
                        if(response_data=="1")
                        {
                            //alert("Confirming");
                            window.location.reload();
                        }
                        else if(response_data=="0")
                            alert("Could not confirm");
                        // as we have written datatype as json so jquery automatically converts the result
                        //from json... so responce_data is not json its already parsed
                    },
                    /*As of jQuery 1.5, the $.ajax() method returns the jqXHR object, which is a superset of the XMLHTTPRequest object.
                    error:  Function( jqXHR jqXHR, String textStatus, String errorThrown )
                    */
                    error: function (xhr, ajaxOptions, thrownError) {
                       // alert("hello");
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
}
            function cancel_delivery(item_id){
            //alert("Inside func cancel");
            $.ajax({
                    url: "cancelajax.php",
                    dataType: "json",
                    type: "GET",
                    data: {
                            item_id : item_id
                            },
                    success: function(response_data){
                    console.log(response_data);
                        if(response_data=="1")
                        {
                           // alert("Cancelling");
                            window.location.reload();
                        }
                        else if(response_data=="0")
                            alert("Could not cancel your order");
                        // as we have written datatype as json so jquery automatically converts the result
                        //from json... so responce_data is not json its already parsed
                    },
                    /*As of jQuery 1.5, the $.ajax() method returns the jqXHR object, which is a superset of the XMLHTTPRequest object.
                    error:  Function( jqXHR jqXHR, String textStatus, String errorThrown )
                    */
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
        }
    </script>

    <script>

        $('#mytabs a').click(function (e) {
       // alert("In function");
          e.preventDefault();
          $(this).tab('show');
       });
    </script>


</body>
</html>
