<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
</head>
<body>
<?php
session_start();
    if(!isset($_SESSION['user_nm']))
    {
        $length=10;
        $charset='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
        $str = '';
        $count = strlen($charset);
        while ($length--) {
            $str .= $charset[mt_rand(0, $count-1)];
            }
        $_SESSION['user_nm'] = $str;
    }
?>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?> 
		</div>
	
		<div class="container-fluid"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->
				<div class="col-sm-3 col-md-2 sidebar">
	                <ul class="nav nav-sidebar" id="category_list">
	                	<?php include_once "index_load_categories.php";?>
		            </ul>
                </div>
				<!--Main Content area--> 
		        <div class="container-fluid col-sm-9 col-md-9">
		        	<div id="item_col_1" class="container-fluid clo-sm-3 col-md-3 col-xs-3"></div>
		        	<div id="item_col_2" class="container-fluid clo-sm-3 col-md-3 col-xs-3"></div>
		        	<div id="item_col_3" class="container-fluid clo-sm-3 col-md-3 col-xs-3"></div>
		        	<div id="item_col_4" class="container-fluid clo-sm-3 col-md-3 col-xs-3"></div>
		           <!--
						Write all
						your code
						here...
						It will appear in the content 
						section of webpage
		           -->
		        
	    		</div>
		</div>
	</div>
	<!--All javascript placed at the end so that the page loads faster-->
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/bootstrap-hover-dropdown.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>
	<script type="text/javascript" src="../js/custom/index_load_items.js"></script>
</body>
</html>
