<!DOCTYPE html>
<?php session_start(); ?>
<?php
require_once "class.MySQL.php";
$omysql=new MySQL();
$output = '';

//collect
$item_id=$_GET["item_id"];
if(isset($_SESSION['authentication'])){
    $row=$omysql->ExecuteSQL("SELECT * from watch_list where user_nm='".$_SESSION['user_nm']."' and item_id='$item_id'");
    if($row!="true")
    {
        $row=$omysql->ExecuteSQL("SELECT `cost` from items where item_id='$item_id'");
        $omysql->ExecuteSQL("UPDATE watch_list SET `previous_cost`='".$row[0]["cost"]."' where item_id='$item_id' and user_nm='".$_SESSION['user_nm']."'");
    }
}
$from = "items";
$where = array("item_id ="=>$item_id);
$query =$omysql->Select($from, $where);

$row =$omysql->arrayedResult;
        $item_nm = $row[0]['item_nm'];
        $pic_loc = $row[0]['pic_loc'];
        $cost = $row[0]['cost'];
        $item_condition = $row[0]['item_condition'];
        $description = $row[0]['description'];
        $type = $row[0]['type'];
        $promotion_amnt = $row[0]['promotion_amnt'];
        $category = $row[0]['category'];
        $author_nm = $row[0]['author_nm'];
        $genre = $row[0]['genre'];
        $brand = $row[0]['brand'];
        $model = $row[0]['model'];
        $sale_type = $row[0]['sale_type'];

?>

<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
        <link rel="stylesheet" type="text/css" href="../css/bootstrap-magnify.min.css">
</head>
<body>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?>
		</div>

		<div class="container"><!-- you can delete this div if you don't want the side bar-->

				<!--Main Content area-->

                                        <h1> <?php print("$item_nm"); ?> </h1>

                                 <div class="row">
                                       <div class="col-md-3" >
                                           <div class="mag">
                                                <?php $pic = "../upload/".$pic_loc; ?>
                                                <img data-toggle="magnify" src="<?php echo $pic;?>" alt="" title="" width="300" height="1000" class="img-thumbnail">

                                           </div>

                                       </div>
                                    <div class="col-md-2 col-md-offset-1">

                                        <h2>
                                           ₹ <?php echo $cost;?>
                                        </h2>
                                       </div>
                                    <div class="col-md-4 col-md-offset-1">
                                        <blockquote>
                                            <ul>
                                                <?php
                                                    if ($item_condition != null){
                                                    echo "<li> Condition: $item_condition </li>";
                                                    }
                                                    if ($brand != null){
                                                    echo "<li> Brand: $brand </li>";
                                                    }
                                                    if ($model != null){
                                                    echo "<li> Model: $model </li>";
                                                    }
                                                    if ($genre != null){
                                                    echo "<li> Genre: $genre </li>";
                                                    }
                                                    if ($author_nm != null){
                                                    echo "<li> Author: $author_nm </li>";
                                                    }
                                                    if ($sale_type != null){
                                                    echo "<li> Sale type: $sale_type </li>";
                                                    }

                                                     $str_explode=explode(";",$description);
                                                    $string1 = $str_explode[0]; // hello
                                                    $string2 = $str_explode[1]; // test
                                                    if($string1 != null){
                                                     echo "<li>$string1 </li>";
                                                    }

                                                ?>
                                            </ul>
                                        </blockquote>
                                        <p>
                                            <button type="button" class="btn btn-primary btn-lg" onClick="add_cart('<?php echo $item_id;?>')">Add To Cart</button>
                                            <button type="button" class="btn btn-primary btn-lg" onClick="add_watch('<?php echo $item_id;?>')" @brand-success: #5cb85c; >Add To Watch List</button>
                                        </p>
                                    </div>
                                </div>

		           <!--
						Write all
						your code
						here...
						It will appear in the content
						section of webpage
		           -->


		</div>
	</div>
	<!--All javascript placed at the end so that the page loads faster-->
        <script src="../js/jquery.js"></script>
        <script src="../js/bootstrap-magnify.min.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>
	<script>
	    function add_cart(item_id)
	    {
            // alert("IN ADD_CART FUNC");
            $.ajax({
                    url: "detail_addcart.php",
                    dataType: "json",
                    type: "GET",
                    data: {
                            item_id : item_id
                            },
                    success: function(response_data){
                    console.log(response_data);
                        if(response_data=="1")
                        {
                           alert("Added");
                            //window.location.reload();
                        }
                        else if(response_data=="0")
                        {
                            alert("Could not be added!!!");
                        }
                        // as we have written datatype as json so jquery automatically converts the result
                        //from json... so responce_data is not json its already parsed
                    },
                    /*As of jQuery 1.5, the $.ajax() method returns the jqXHR object, which is a superset of the XMLHTTPRequest object.
                    error:  Function( jqXHR jqXHR, String textStatus, String errorThrown )
                    */
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
	    }
	    function add_watch(item_id)
	    {
            // alert("IN ADD_watch FUNC");
            $.ajax({
                    url: "detail_addwatch.php",
                    dataType: "json",
                    type: "GET",
                    data: {
                            item_id : item_id
                            },
                    success: function(response_data){
                    console.log(response_data);
                        if(response_data=="1")
                        {
                            alert("Added");
                            //window.location.reload();
                        }
                        else if(response_data=="0")
                        {
                            alert("Could not be added!!!");
                        }
                        // as we have written datatype as json so jquery automatically converts the result
                        //from json... so responce_data is not json its already parsed
                    },
                    /*As of jQuery 1.5, the $.ajax() method returns the jqXHR object, which is a superset of the XMLHTTPRequest object.
                    error:  Function( jqXHR jqXHR, String textStatus, String errorThrown )
                    */
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status);
                        alert(thrownError);
                    }
                });
	    }
    </script>
</body>
</html>
