<!DOCTYPE html>
<?php require_once "check_session.php";?>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="../css/bootstrap-amazon.css">
</head>
<body>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?> 
		</div>
	
		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->
			
				<!--Main Content area--> 
		        <div class="container-fluid col-sm-9 col-md-9">
		           <!--
						Write all
						your code
						here...
						It will appear in the content 
						section of webpage-->
				<div class="a-section a-spacing-double-large">
					<div id="summary" class="a-section a-spacing-extra-large a-padding-none">

    				<div class="a-divider a-divider-section">
        				<div class="a-divider-inner">
        				<font size="5">
    					<b>
		           
		           <?php  
				           
				           require_once "class.MySQL.php"; 
				           $mmysql=new MySQL();
				           if(isset($_SESSION["item_id"]) && isset($_GET["bid"])){
				           		$item_id = $_SESSION['item_id'];
				              	$bid = $_GET['bid'];
            					$where =array("item_id like"=>$item_id."%");
            					$mmysql->Select("items",$where);
            					if($mmysql->records>0){
            						$result = $mmysql->arrayedResult;
            						foreach($result as $row){
            							$base_price=$row["base_price"];
            							$mrp=$row['cost'];
            						}
	
				           		}

				           		$nmysql=new MySQL();
            					$limit=1;
				              	$nwhere = array("item_id like"=>$item_id."%");
					            $nmysql->Select("auction_bidder",$nwhere,"bid DESC",$limit);
					            if($nmysql->records>0){
					             	$result = $nmysql->arrayedResult;
					                foreach($result as $row){
					                	$cur_bid=$row["bid"];
					                }
					                
					            }else{
					                	$cur_bid=$base_price;
					                }

				            require_once "class.MySQL.php";           
				            $omysql=new MySQL();
					            if($bid > $cur_bid){
					              $vars = array('user_nm'=>$_SESSION["user_nm"],'item_id'=>$item_id,'bid'=>$bid);
					              $omysql->Insert($vars,"auction_bidder");
					              echo "Your bid has been saved.Please keep checking the bid.";
					            }
					            else{
					              echo "your bid could not be placed as the bid value is less than current bid";
					            }

					            $set=array("base_price"=>$bid);
					            $where=array("item_id like"=>$item_id."%");
					        	$omysql->Update("items",$set,$where);
				        }

				            
				?>
						</b>
						</font>
						</div>

		        </div>

		        </div>

	    		</div>
	    		
		</div>
	</div>
	<!--All javascript placed at the end so that the page loads faster-->
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>
</body>
</html>
