<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
	<style type="text/css">
	input[type=submit] {
    width: 7em;  height: 3em;
	font-size:15px;}
	input[type=number]{
	border:bold;
	    padding:10px;
		margin:30px;
		width:30%;
		autofocus;
		font-size:20px;
	}
	</style>
</head>
<body>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?> 
		</div>
	
		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->
				<div class="col-sm-3 col-md-2 sidebar">
	                <ul class="nav nav-sidebar">
		                 <li class="active"><a href="#">Search</a></li>
		                <li class="active"><a href="new_orders.php">New Orders</a></li>
		                <li class="active"><a href="approved_orders.php">Approved Orders</a></li>
		                <li class="active"><a href="set_threshold.php">Set Threshold</a></li>
		                <li class="active"><a href="vendors.php">Items Store</a></li>
		                <li class="active"><a href="bulk_logout.php">Log Out</a></li>
		                <li class="active"><a href="#">Help</a></li>
	     

	                </ul>
                </div>
				<!--Main Content area--> 
		        <div class="container-fluid" >
		        	<?php
		        	include_once "admin_shipment_requirements.php";
							        		        	?>
		        		        	<form action="set_min_thresolds.php" method="POST"> 
									<label >Current min_count thresold is <?php echo get_min_no_of_items();?></label>
									<br>
									<label >Current min_amount thresold is Rs:<?php echo get_min_total_cost(); ?></label>
									<br>
		        		        		<label >How much min_count and min amount thresolds would you like to set:</label>
										<br>
										
										<input type="number" name="min_count" placeholder="thresold_number_of_items"/>
										<input type="number" name="min_amount" placeholder="thresold_amount" />
										<input type="submit" name="update" value="update" />
		        		        	 </form> 
									
									
									
		           <!--
						Write all
						your code
						here...
						It will appear in the content 
						section of webpage
		           -->
		        
	    		</div>
		</div>
	</div>
	<!--All javascript placed at the end so that the page loads faster-->
    <script src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>
</body>
</html>
