<!DOCTYPE html>
<!-- Do not edit this file, copy the code to use it in your module-->
<html>
<head>
	<meta charset="utf-8">
    <title>Template</title>
	<link rel="stylesheet" href="../css/bootstrap.css"  type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../css/smoothness/jquery-ui.css">
	
</head>
<body>
	<div class="container-fluid">
		<div class="row" role="header">
			<?php include_once "header.php";?> 
		</div>
	
		<div class="container"><!-- you can delete this div if you don't want the side bar-->
				<!--Navigation sidebar-->
				<div class="col-sm-3 col-md-2 sidebar">
	                <ul class="nav nav-sidebar">
		                <li class="active"><a href="#">Search</a></li>
		                <li><a href="#">Profile</a></li>
		                <li><a href="#">Bulk Order</a></li>
		                <li><a href="#">Sell</a></li>
	                </ul>
                </div>
				<!--Main Content area--> 
		        <div class="container-fluid col-sm-9 col-md-10">
		           <!--
						Write all
						your code
						here...
						It will appear in the content 
						section of webpage
		           -->
		           <!--
		           <?php //require_once "check_session.php";?>
		           -->
		           <!--<div class="control-group">
		             <label class="control-label" for="select01">Choose Type</label>
		             <div class="controls">
		             <select name="choosen_type" id="select01">
		             <option></option>
		             <option>Auction</option>
		             <option>Sale</option>
		             </select>
		             </div>
		           </div>-->
                   <div class="control-group">
		             <label class="control-label" for="select02" >Choose Category</label>
		             <div class="controls">
		             <select name="category" id="sel">
		             <option></option>
		             <option value='Electronics'>Electronics</option>
		             <option>Books</option>
		             <option>Stationery</option>
		             <option>Appliances</option>
		             <option>Others</option>
		             </select>
		             </div>
		            
		             <!--<label class="control-label" for="select02">Choose Category</label>
		             <div class="controls">
		             <select name="category" id="sel">
		             <option></option>
		             <option value="Electronics">Electronics</option>
		             <option>Books</option>
		             <option>Stationery</option>
		             <option>Appliances</option>
		             <option>Others</option>
		             </select>
		             </div>-->
		             <!--<button onclick=" func()">Sale</button>-->
		             <!--<input type="button" value="Marks check" onclick='func()' />-->
		            
		             <!--<button onclick="window.location.href='auction.php'; ">Auction!</button>-->
		              <input type="submit" name="submit" class="btn btn-primary" value="Auction" onClick="x=document.getElementById('sel').value;
		              if(x=='Electronics'){
		              window.location.href='electronic_auc.php';
		              }
		              else if(x=='Books'){
		              window.location.href='books_auc.php';
		              }
		              else if(x=='Stationery'){
		               window.location.href='stationary_auc.php';
		              }
		              else if(x=='Appliances'){
		              window.location.href='appliances_auc.php';
		              }
		              else if(x=='Others'){
		              window.location.href='others_auc.php';
		              }
		              else{

		              alert('Choose something');
		              }
		              ;">

		               <input type="submit" name="submit" class="btn btn-primary" value="Sell" onClick="x=document.getElementById('sel').value;
		              if(x=='Electronics'){
		              window.location.href='electronic_sale.php';
		              }
		              else if(x=='Books'){
		              window.location.href='books_sale.php';
		              }
		              else if(x=='Stationery'){
		               window.location.href='stationary_sale.php';
		              }
		              else if(x=='Appliances'){
		              window.location.href='appliances_sale.php';
		              }
		              else if(x=='Others'){
		              window.location.href='others_sale.php';
		              }
		              else{

		              alert('Choose something');
		              }
		              ;">
		           </div>
           


                <!--alert(document.getElementById('sel').value);

                 if(document.getElementById('sel').value == 'Books' 
		               then
		                window.location.href='login.php'; 
		                -->
                

                    
		        
	    		</div>
		</div>
	</div>
	<script type="text/javascript">
		function func(){
			alert(document.getElementById('sel').value);
			//alert(document.getElementById("select02").value);
			//<?php if($_REQUEST['category'] == 'Electronics'){ echo(' selected ');
		}
	</script>
	<!--All javascript placed at the end so that the page loads faster-->

    <script type="text/javascript" src="../js/jquery.js"></script>
	<script type="text/javascript" src="../js/bootstrap.js"></script>
	<script type="text/javascript" src="../js/jquery-ui.js"></script>
	<script type="text/javascript" src="../js/custom/search_suggestions.js"></script>

</body>
</html>
